builders:
  fireproof:
    import: "package:fireproof/src/fireproof_base.dart"
    builder_factories: ["fireproofBuilder"]
    build_extensions: {".dart": [".fireproof.dart"]}
    auto_apply: dependents
    build_to: source
    # required_inputs: ["*.g.dart"]
