name: fireproof
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  change_case: ^2.0.1

dev_dependencies:
  analyzer: '>=5.2.0 <7.0.0'
  lints: ^3.0.0
  test: ^1.25.1
  build_runner: ^2.4.8
  source_gen: ^1.5.0
  build: ^2.4.1
  json_annotation: ^4.8.1
